# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-08 17:16
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields
import wagtail.wagtailimages.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_blogpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='blogElement',
            field=wagtail.wagtailcore.fields.StreamField((('heading', wagtail.wagtailcore.blocks.CharBlock(classname='full title')), ('paragraph', wagtail.wagtailcore.blocks.TextBlock()), ('picture', wagtail.wagtailimages.blocks.ImageChooserBlock())), default=[]),
        ),
    ]
